### PR TITLE
schedule: add Code of Conduct and Diversity discussion

### PR DESCRIPTION
**Pull request by davecheney**
/cc @enneff @sarahadamscodes @campoy

Hello,

Please review this inclusion to the schedule. 

When this is live this link, http://gophercon.com/schedule/10july/#diversity can be used to tweet the specific part on the schedule page.

### CODE REVIEW

**Comment by campoy** [comment]
LGTM

**Comment by adams-sarah** [comment]
Looks great.
Please note that I had to head home early, so I believe Peggy will be taking my place helping @nf out.

Though, I haven't heard back from him about this change.

Cheers

**Comment by nf** [comment]
LGTM

**Pull request merged**
